### PR TITLE
Defering CSS loading

### PR DESCRIPTION
**Pull request by brunosabot**
Hi,

this PR is here to solve the #24 issue.
The solution is based on https://web.dev/defer-non-critical-css/

### CODE REVIEW

**Comment by weirdpattern** [comment]
Hi @brunosabot no, everything is fine. Sorry I did get to this sooner.
I will merge now and publish tonight.

**Comment by santiq** [comment]
@weirdpattern Hi there! Can you publish this update? 
Thanks!

**Comment by weirdpattern** [comment]
Hey @santiq I'm working on this tonight, but some of the tests are failing for me, so I'm reviewing the merged commits.
I will post another update in a few hours. 

Sorry for the delay... I've work in healthcare and things are going crazy at work.

**Comment by weirdpattern** [comment]
All right people, v1.1.10 is finally out.

I apologize for the long wait, hopefully the wait will be worth it.
Reach out to me if you have questions comments or concerns.

**Pull request merged**
