### PR TITLE
fix(gatsby-ssr): fix URL of embedded default CSS

### PR DESCRIPTION
**Pull request by chitoku-k**
The URL currently injected now returns 404 Not Found. This PR fixes it to a new one.

### CODE REVIEW

**Comment by weirdpattern** [comment]
Hey @chitoku-k thanks for the contribution.

I don't know exactly when this started to happen, but glad you caught it.
I will merge this and probably work on top of this PR, wanna see if I can move this to a setting so that people don't depend on the plugin getting fixed should this happen again...

thoughts? comments?

**Comment by chitoku-k** [comment]
Hi, I saw your work on the configurable URL here (https://github.com/weirdpattern/gatsby-remark-embed-gist/commit/acdcdce4f2b529c5d7057f0d0b01a89af5990fe8).

How about dynamically extract `stylesheet` around here?

https://github.com/weirdpattern/gatsby-remark-embed-gist/blob/dad5464aa6814253c84e27ab23e03f208225fb8b/src/index.js#L125-L138

It looks like the response includes `stylesheet` as a property 

```json
{
  "description": "...",
  "public": true,
  "created_at": "...",
  "files": [],
  "owner": "chitoku-k",
  "div": "...",
  "stylesheet": "https://github.githubassets.com/assets/gist-embed-b3b573358bfc66d89e1e95dbf8319c09.css"
}
```

I currently have no idea as to how this URL could be shared with `gatsby-ssr.js`, but this URL should be used instead.

And, thanks for any efforts made this package happen! I'd love to help with it if interesting.

**Comment by chitoku-k** [comment]
As a spec, `<link rel="stylesheet" />` is categorized as a `body-ok`, which enables us to put them with Gist altogether in a valid way. But somehow ugly...?

https://html.spec.whatwg.org/multipage/links.html#body-ok

**Comment by weirdpattern** [comment]
Hey @chitoku-k let's continue this conversation in #9.

**Pull request merged**
