### PR TITLE
refactor: move url in gatsby-ssr and index.js to settings

### PR DESCRIPTION
**Pull request by weirdpattern**
This PR will:
- move url in gatsby-ssr and index.js to settings
- update dependencies
- simplify build process

### CODE REVIEW

**Comment by weirdpattern** [comment]
OK, this is a follow up to [this comment](https://github.com/weirdpattern/gatsby-remark-embed-gist/pull/8#issuecomment-463256326)...

>As a spec, `<link rel="stylesheet" />` is categorized as a `body-ok`, which enables us to put them with Gist altogether in a valid way. But somehow ugly...?
> https://html.spec.whatwg.org/multipage/links.html#body-ok

Yes @chitoku-k you are right, this can be included in the body, my only concern is the duplication this will cause. If we take the CSS from the JSON and render it as part of the gist itself, then it will be rendered n times (1 per gist in your markdown), which will create a lot of unnecessary traffic in a site (and yes I'm aware this gets cached, but still)... 

Couple of options I can think of:
1. We can check if the stylesheet has already been loaded by a previous call, but I don't know if we have the full context (i.e. loaded html) at this point...
2. We can have a dummy gist and call it from gatsby-ssr to get that stylesheet, but it comes with a price (both performance and the risk of the gist getting deleted).
3. Not sure if github has an API that we can leverage to get this information. I can look into it...

And finally...

>And, thanks for any efforts made this package happen! I'd love to help with it if interesting.

Of course!, feel free to submit as many bugs, suggestions and PRs as you want. I'm always looking for ways to improve the plugin 👍

**Comment by chitoku-k** [comment]
Thanks @weirdpattern for quick response. The duplication could be detected when making use of `cache` object passed down to our function. So, the first occurrence of Gist should preserve its existence to the cache and the others should find it. About 2, I agree with the potential risk you mentioned.

**Comment by weirdpattern** [comment]
@chitoku-k I'm releasing your change as a hotfix, people have started complaining about this.
Let's continue this conversation in this pull request, I will create a backing bug for this.

**Comment by weirdpattern** [comment]
This will be handled in a different way

**Pull request closed without merging**
